### ISSUE TITLE
Bind translation to "Hidden apps" menu heading. Fix rename panel.

### ISSUE THREAD

**Issue by ongots** [jooooscha/Olauncher#115]
![Screenshot_2022-07-25-21-00-30](https://user-images.githubusercontent.com/43604031/181067099-cfdaad95-6f42-4b58-bfe1-620b8619fc9b.jpg)

**Comment by jooooscha** [comment]
Again, please use the issue template

**Comment by ongots** [comment]
This translation works for "Hidden apps" in settings, but doesn't work for "Hidden apps" section header.
https://github.com/jooooscha/Olauncher/blob/e61aa360885cf30cffed6b17ca00e0468ff645f1/app/src/main/res/values-ru/strings.xml#L60


The name of the application does not fit in the rename panel. You need to split the panel into 2 lines.

**Comment by Ilithy** [comment]
Hi;
I validate the first point, the application does not use this line but hardcoded data, if I'm not mistaken (I'm not a developer).

for the second point raised, it already is, see my capture of the hidden app panels:

![Hidden app panel](https://i.ibb.co/r4GNdsZ/Screenshot-20220727-063157.png)

For this issue, It seems to come from your operating system rather than the launcher

**Comment by ongots** [comment]
![Screenshot_2022-07-27-13-07-36](https://user-images.githubusercontent.com/43604031/181233882-565a5c58-a790-449b-a0b3-ee030ced52ee.jpg)
![Screenshot_2022-07-27-13-00-25](https://user-images.githubusercontent.com/43604031/181233919-083694e3-07c7-4c84-9194-0957dc515961.jpg)
My screen is 5.5"
By the way, opening the rename panel does not hide the previous one.

**Comment by jooooscha** [comment]
Again, please use the issue templates, and please do not report multiple problems in one issue. Otherwise it's hard to keep on overview
