### ISSUE TITLE
App groups on homescreen

### ISSUE THREAD

**Issue by Falciform** [jooooscha/Olauncher#121]
Hey

First things first. I love the launcher you created!

Second. Would you evaluate if it's doable to add a way of grouping apps? 
Messaging applications, work applications, ...

Thx for reviewing my request!

(Is it normal that i can't label this as feature request? )

**Comment by Ilithy** [comment]
Hi;

> (Is it normal that i can't label this as feature request? )

Yes it's normal, because you didn't use the template for the feature request, it would have been more convenient to use it ;-)

I'm not sure that this corresponds to the principle of a minimalist launcher, the developer has already allowed up to 15 apps to be placed on the home screen, adding folders would multiply the number of clicks necessary to access an app; But that's just my opinion ;-)

**Comment by jooooscha** [comment]
This would be possible, but the main flow should be: swipe up, search for an app. Only apps you absolutely need often or fast should be placed on the home screen. Any other flow like categorizarion, sorting apps differently, etc. are non-features of this fork
