### ISSUE TITLE
Double tap to sleep

### ISSUE THREAD

**Issue by lichingyun** [jooooscha/Olauncher#15]
I have a problem using OCF: I can't use the last settings option (double tap to sleep)
I have activate this option (working with the original Olauncher)
but in OCF I have activate it but when I double tap on the screen nothing happens
@jooooscha can you help me please?

**Comment by jooooscha** [comment]
I can confirm that it is not working.

Sadly, I did not (consciously) change anything regards this feature. Therefore, I cant think of a fast solution. I will look into it as soon as I have the time

**Comment by lichingyun** [comment]
no problem joscha, take your time 🙏
I am not a programmer, maybe is a problem of permissions 🤔

**Comment by cyrdam** [comment]
Same issue for me. What I did is to try out your fork without uninstalling the old one. Maybe this is related.

**Comment by jooooscha** [comment]
This should be fixed. Although, I did have some issues if another accessibility service was enabled. Also sometimes I needed to enable, then disable, then enable the service again. Otherwise, android would report that the service was broken. Idk, this seems to be very weird behavior, Please report if you have any further issues
