### ISSUE TITLE
Icons and Icon Packs

### ISSUE THREAD

**Issue by wildebeest3** [jooooscha/Olauncher#40]
Would it be possible to have icons for apps to the left of the app names? Its sometimes easier/faster to identify apps based on their icons. Maybe it would be possible to change whether you want icons to display on the homescreen or the app drawer

**Comment by TettaVolante** [comment]
Although I agree that  that icons are easier to spot quickly, I think that adding icons would defeat the minimalistic purpose of the launcher. Adding a first letter separation and a quick alphabet indexer in the app drawer would definitely make the navigation easier.
If you want an alternative (foss) mechanically similar to olauncher there's KISS launcher, otherwise there's niagara launcher (proprietary).

**Comment by ferlanero** [comment]
I agree adding icons would truncate the minimalistic feeling of Olauncher Clutter Free. There are other launchers out there with this feature already implemented as commented before.
