### ISSUE TITLE
Community Question: Font Size

### ISSUE THREAD

**Issue by jooooscha** [jooooscha/Olauncher#42]
I am unsure which settings are useful for the font size. Therefore I am asking you:

- If know how to work with Android Studio, to try some different font sizes (Change the TEXT_SIZE constants in Contstants.kt) and tell me you favorites
- Otherwise, you can still tell be relative to the current values of Huge, Normal, and Small if you would like to have smaller or bigger values

Thanks for everyone participating ❤️

**Comment by lichingyun** [comment]
Hello @jooooscha 
for me the font size is perfect, I like to use the normal or the small size
depending on the wallpaper I use 😃
personally I use my phone at 490 dpi

**Comment by TettaVolante** [comment]
Rather than between three arbitrarily predefined sized, it would be better to let the user choose the size of the font.

Quick and simple mockup:
![text size ](https://user-images.githubusercontent.com/105862850/171600165-ddf0eaa9-74b3-4af6-ae0f-b2d768310f80.jpg)
Behavior:
'-' reduces font size of 2 units
'+' increments font size of 2 units
'number' inserts custom number via keyboard

Ideally there would be a live preview on screen so the user doesn't have to open and close the options panel every time to see the difference.

**Comment by jooooscha** [comment]
This is a good idea. I will see what I can do

**Comment by jooooscha** [comment]
will be added in #30
