### ISSUE TITLE
Possible to tie into notifications in some way?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [jooooscha/Olauncher#46]
Hello! In order to know whether I've missed a call or received a text or email, I have to rely on the status bar notifications or open the apps individually to check. Is there any way an indicator could be shown on the home screen's app listing itself? This might allow for greater visibility and also make it more feasible to hide the status bar altogether.

Thanks for your great fork!

**Comment by jooooscha** [comment]
This does crash a little with this being a minimal, non-disturbing, non-attention grabbing, launcher.
Further, this would requiere more permission (Permission to read notifications). Therefore, I am a bit against this (but of course always open for discussions)

**Comment by Blake-LeBlanc** [comment]
Yes, I see what you mean. One of the main draws for the minimal look is to have it be very stripped down.

I'm not used to relying on the status bar, so maybe I just need to give it some time! 

Just out of curiosity, how do you handle it? Do you always display the status bar or do you tap into each program individually to check? Or something else?

**Comment by jooooscha** [comment]
I have the status bar disabled, and if I want to know if I have notifications I pull the status bar down

**Comment by Blake-LeBlanc** [comment]
Okay, I'll try that too!

**Comment by aberonni** [comment]
Hey @jooooscha, I think this launcher might gain some traction due to being a great option for new minimalist phones based on Android, such as the Mudita Kompakt. See, for example, [this thread](https://forum.mudita.com/t/which-text-based-launcher-are-you-using-with-your-kompakt/8992/17).

The problem with the Kompakt and most launchers out there (including yours) is that there _is_ no status bar - and the launcher is the only way to see if there are notifications.

So I wonder if that would change your stance on the above? If not (and I would understand, especially due to the permissions side of things), would you be willing to point me towards where to start looking at the code to add a feature like this? I have no experience with Android development, but I imagine that adding this feature shouldn't be too complex if one knows where to look.

Thanks!
