### ISSUE TITLE
Redesign settings, Perfecting the translation of parameters

### ISSUE THREAD

**Issue by Ilithy** [jooooscha/Olauncher#61]
Hi,
In the spirit of improving the settings, would it be possible to make these terms translatable:

![IMG_20220616_092429__01](https://user-images.githubusercontent.com/36798218/174016701-469d88c6-eca4-43bd-b14b-01e129c6ad80.jpg)

Thank you

**Comment by jooooscha** [comment]
The problem is that those are the names of the apps, you've selected. We would need to have a translation for every single app. Wouldn't we?

**Comment by Ilithy** [comment]
Weird because no, on my phone (Pixel 6 pro under GrapheneOS) the applications do not have these names (for example, my dialer application is called Koler), and are not displayed (in the UI of Olauncher CF) in the language of the system (on my device, the language is French, modified just for the screen capture)

This is not critical, and does not really pose a problem, it can be set aside.

**Comment by TettaVolante** [comment]
Even weirder because works as intended on my device
![Screenshot_20220619-104549_Olauncher](https://user-images.githubusercontent.com/105862850/174473129-6857b18f-d9b2-46bd-bc01-102dcac9feb3.png)

Did you modify the stock settings? iirc both calendar and clock were in English before I modified the option choosing the app from the drawer.

**Comment by Ilithy** [comment]
@TettaVolante Indeed, it comes from that, after reselection of the zpps, they appear with their correct name, so it is not annoying, I will close this thread with your agreement, thank you.
