### ISSUE TITLE
Shortcuts Color

### ISSUE THREAD

**Issue by lichingyun** [jooooscha/Olauncher#64]
Hello @jooooscha 

I have an idea to make OCF more configurable:
is possible to put in the settings the possibility to choice the color of the shortcuts? with the dark theme the writings are white, with the white theme the writings are black, but with some wallpaper the black or white writings are unreadable.

Thanks

**Comment by TettaVolante** [comment]
Even better would be following android 12 conventions and let the app change the text color according to the wallpaper. Admittedly I have yet to try android 12 so I don't know if it chooses the right colors.

**Comment by lichingyun** [comment]
> Even better would be following android 12 conventions and let the app change the text color according to the wallpaper. Admittedly I have yet to try android 12 so I don't know if it chooses the right colors.

no, I think this is not a good idea. is betterto let the user to choice the color he like (especially if the user have some problem in his eyes like me).
Out of topic: @TettaVolante are you italian like me?

**Comment by TettaVolante** [comment]
Well the implementation of one doesn't impede the other, I believe the base framework (making the text change color) should be the same for both features. 
@lichingyun why, yes how did you figure? /s

**Comment by lichingyun** [comment]
> Well the implementation of one doesn't impede the other, I believe the base framework (making the text change color) should be the same for both features. @lichingyun why, yes how did you figure? /s

maybe you are right, I am not a programmer.

@TettaVolante because I am italian too 🤣🤣🤣

**Comment by jooooscha** [comment]
This is a good point. I keep this in mind

**Comment by Ilithy** [comment]
Hello, I take the liberty to intervene to ask the developer if, with the future migration of Olauncher CF to Jetpack compose, we will have the chance to see Olauncher support monet (and dynamic adaptive theme), it would be very nice because it tints the whole interface, as the color of accentuation of the quick tiles, buttons etc...
it's the biggest visual evolution of android 12, it's really a shame not to have access to it with a launcher as elegant as Olauncher CF, thank you very much for the huge work already done <3

**Comment by jooooscha** [comment]
Tracked  in #95
